// Generated by tools/palette_builder.py - do not edit by hand.
//
// Distinguishable flow colours are a gameplay requirement, not a styling
// choice. Every palette below is verified to keep a CIE76 distance of at
// least 22 between any two of its colours before it ships.

public extension CosmeticCatalog {

    /// Flow colours per palette id, indexed by colour number.
    static let paletteColors: [String: [String]] = [
        "aurora": [
            "#DE3535", "#EAA77B", "#F37F20", "#F3C920",
            "#C0F76E", "#20F320", "#20F3B4", "#20C9F3",
            "#207FF3", "#2020F3", "#DE20F3", "#EA7BDF",
            "#F3208A", "#EA7B97",
        ],
        "tide": [
            "#DF1616", "#DE817C", "#DF8416", "#DEC67C",
            "#DFDF16", "#9CE773", "#16DF16", "#7CDEBC",
            "#3198C4", "#1670DF", "#1616DF", "#D07CDE",
            "#CB16DF", "#DF1666",
        ],
        "ember": [
            "#E3641C", "#ECB765", "#FAE405", "#A7EC65",
            "#05FA08", "#55FCB2", "#55C8FC", "#1188EE",
            "#0558FA", "#0805FA", "#BE65EC", "#CB05FA",
            "#FA05AE", "#FA0558",
        ],
        "circuit": [
            "#F49052", "#FFCE1F", "#C9F500", "#13E60F",
            "#52F488", "#2CF2D0", "#47DEFF", "#0F94E6",
            "#075CED", "#0700F5", "#D91FFF", "#F452C7",
            "#F45276", "#F5001D",
        ],
        "orchid": [
            "#E8B891", "#F28F2C", "#F2F22C", "#C5E891",
            "#8FF22C", "#2CF285", "#57F4CD", "#82E0F7",
            "#57A6F4", "#2C71F2", "#2C2CF2", "#D945CA",
            "#E891B8", "#F22C5D",
        ],
        "glacier": [
            "#DE715E", "#E2CCB6", "#DEAB5E", "#DEDE5E",
            "#CCEEAA", "#5EDE85", "#69D3D3", "#69A9D3",
            "#5E85DE", "#715EDE", "#C98CDE", "#DE5EDE",
            "#DE5E98", "#EEAAC5",
        ],
        "dusk": [
            "#D06E6C", "#E0792E", "#D0AF6C", "#E0C92E",
            "#7CB72A", "#2EE032", "#36AB67", "#56D5E6",
            "#2E8CE0", "#5B36AB", "#E02EDC", "#D06CC4",
            "#E02E7B", "#E02E34",
        ],
        "nebula": [
            "#FA6205", "#EB9F6F", "#EDB212", "#E6FA05",
            "#0AFA05", "#05FAAC", "#05DAFA", "#0584FA",
            "#0C05FA", "#C46FEB", "#D005FA", "#FA05B5",
            "#EB6F9D", "#FA0553",
        ],
    ]
}
